# Configuration for binary violence classification

data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  image_size: [224, 224]
  channels: 3
  batch_size: 32
  num_workers: 4
  pin_memory: true
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  use_augmentation: true
  horizontal_flip_prob: 0.5
  rotation_degrees: 10
  color_jitter: true
  max_images_per_class: null
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

model:
  model_type: "resnet18"
  num_classes: 2
  dropout_rate: 0.3
  pretrained: true
  feature_dim: 512
  use_attention: true
  hidden_size: 512
  use_spatial_attention: true
  use_context_analysis: true

training:
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  momentum: 0.9
  scheduler: "reduce_on_plateau"
  scheduler_patience: 7
  scheduler_factor: 0.5
  loss_function: "cross_entropy"
  label_smoothing: 0.1
  focal_alpha: 1.0
  focal_gamma: 2.0
  early_stopping_patience: 15
  gradient_clip_value: null
  save_best_only: true
  save_every_n_epochs: 10
  val_check_interval: 1

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "auc", "confusion_matrix"]
  batch_size: 64
  threshold: 0.5
  plot_confusion_matrix: true
  plot_roc_curve: true
  plot_precision_recall: true
  save_plots: true
  class_names: ["Non-Violence", "Violence"]

logging:
  log_level: "INFO"
  use_tensorboard: true
  use_wandb: false
  wandb_project: "epra-binary-classifier"
  experiment_name: null
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  log_every_n_steps: 10
  save_model_every_n_epochs: 5

inference:
  checkpoint_path: null
  model_type: "binary"
  batch_size: 1
  device: "auto"
  return_probabilities: true
  return_features: false
  output_format: "dict"
  confidence_threshold: 0.5
  apply_smoothing: false

system:
  device: "auto"
  mixed_precision: true
  random_seed: 42
  deterministic: true
  compile_model: false
  project_root: ""
  data_root: "data"
  output_root: "outputs"

